M48
; DRILL file {KiCad 8.0.3-8.0.3-0~ubuntu22.04.1} date 2025-02-10T22:14:24+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-10T22:14:24+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3-8.0.3-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
%
G90
G05
T1
X105.605Y-64.61
X105.605Y-70.39
T2
X104.0Y-77.0
X113.0Y-62.0
X137.0Y-64.0
M30
